### ISSUE TITLE
Support alternator API

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1095]
We should support ScyllaClusters with alternator API.

```[tasklist]
- [ ] https://github.com/scylladb/scylla-operator/issues/1405
- [ ] https://github.com/scylladb/scylla-operator/issues/1732
- [ ] https://github.com/scylladb/scylla-operator/issues/1082
- [ ] https://github.com/scylladb/scylla-operator/issues/1081
- [ ] https://github.com/scylladb/scylla-operator/issues/1080
- [x] Manage Alternator certificates
- [ ] https://github.com/scylladb/scylla-operator/issues/1743
```

**Comment by tnozicka** [comment]
done
