### ISSUE TITLE
Expose ScyllaDB to external clients and other datacenters

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1270]
Currently, scylla operator exposes every ScyllaDB nodes with a service of type ClusterIP and sets the ClusterIP to be published by ScyllaDB nodes. ClusterIPs are virtual IPs that can't be reached out from outside of the cluster. Given they are virtual it's even hard to hack to route the external traffic to the cluster manually. It doesn't even matter if you setup LBs to expose the nodes manually because ScyllaDB will publish the internal IP to the external clients that will pick those up and fail.

To be able to reach the nodes from another DC or an external client, we need scylla to publish different IPs. Depending on the use case, the IP adresses can come from the Pod IP (when https://github.com/scylladb/scylladb/issues/6403 gets implemented) or different types of services, like LoadBalancer. With all the other service options we don't support, some of them control whether say the LB provides private or public IP. Maybe we should add a serviceTemplate field or a metadata template (to avoid conflicts) so it's easily controllable.

To sum up the expose options:
- Pod IPs allow exposing  pods in internal IPs to other DCs
- Service.type==LoadBalancer can allocate both external and internal IPs (internal ones are still useful to avoid VPC peering)
- Possibly this could be ingress based URL

Ideally we should abstract the current logic not to use IPs, or at least dynamically fetch them when necessary (like with `replace_address_first_boot`), so it we can then implement a switch specifying which ones to use. Picking the source of them will likely be less work then the abstraction work.

If we decide to make a switch specifying which type to use, it would allow us to implement this and maintain backwards compatibility. Given we'll eventually need both PodIP and LB, the switch seems reasonable to start with.

This needs to start with a design doc.
```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylla-operator/pull/1297
- [ ] https://github.com/scylladb/scylla-operator/issues/1277
- [ ] https://github.com/scylladb/scylla-operator/issues/1315
- [ ] https://github.com/scylladb/scylladb/issues/6403
- [ ] https://github.com/gocql/gocql/issues/831#issuecomment-272060425
- [ ] https://github.com/scylladb/scylla-operator/issues/1319
- [ ] https://github.com/scylladb/scylla-operator/issues/1380
```

**Comment by tnozicka** [comment]
Old link made a subtask to close this but this is still open (implementation landed)

**Comment by tnozicka** [comment]
done
