### ISSUE TITLE
Complete ScyllaDB operations procedues

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1362]
We should audit the operations that ScyllaDB requires to this date and update our operating procedures if needed.

```[tasklist]
- [ ] Procedure audit - possibly based on https://docs.google.com/document/d/1xJNvx9Zuf-DNi8ao0ZT1iJnFqDTqvkcAVVGXNqVA2LA/edit
- [ ] https://github.com/scylladb/scylla-operator/issues/1358
- [ ] https://github.com/scylladb/scylla-operator/issues/1208
````
