### ISSUE TITLE
Add restore procedure using Scylla Manager

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1387]
The [current restore procedure](https://operator.docs.scylladb.com/stable/nodeoperations/restore.html) is fairly manual, slow and @zimnx mentioned that it has a size limit as well. We should migrate to using the Scylla Manager for the restore.

```[tasklist]
- [ ] Create design doc for restore using Scylla Manager
- [ ] Implement support for restore using Scylla Manager in the Operator
- [x] Replace sstable based restore procedure with manager
```

**Comment by mflendrich** [comment]
Will be tracked in https://github.com/scylladb/scylla-operator/issues/2417.
