### ISSUE TITLE
Support arm64

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1412]
ScyllaDB supports running on `arm64` and `amd64` and also publishes container images for both of them. So far the operator has been building and testing only on `amd64`. This epic tracks adding arm64 to the operator as well.

```[tasklist]
- [ ] https://github.com/scylladb/scylla-operator-images/issues/25
- [ ] https://github.com/scylladb/k8s-local-volume-provisioner/issues/23
- [ ] https://github.com/scylladb/scylla-operator/issues/1409
- [x] Make sure scylla-manager images contain arm64 platform as well
- [ ] https://github.com/scylladb/scylla-operator/issues/1410
- [ ] https://github.com/scylladb/scylla-operator/issues/1411
```

```
$ podman manifest inspect docker.io/scylladb/scylla:latest
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "manifests": [
        {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 595,
            "digest": "sha256:67d184afed551cb23435c7d1a333e37c1793d764e7f1e7a3501c8dcfc94fc58e",
            "platform": {
                "architecture": "arm64",
                "os": "linux"
            }
        },
        {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 595,
            "digest": "sha256:03892c6b07a62af690f2cc970b9fb5e50d981a82f2269db87a52c3e96477f413",
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    ]
```

**Comment by rzetelskik** [comment]
@tnozicka shouldn't we add building [k8s-local-volume-provisioner](https://github.com/scylladb/k8s-local-volume-provisioner) for arm64 as well?

**Comment by tnozicka** [comment]
> @tnozicka shouldn't we add building [k8s-local-volume-provisioner](https://github.com/scylladb/k8s-local-volume-provisioner) for arm64 as well?

good point, added https://github.com/scylladb/k8s-local-volume-provisioner/issues/23
