### ISSUE TITLE
Support manual storage expansion in place

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1572]
We need to test and document a way to grow storage when there is space at the same node. At this point, due to some upstream limitation with StatefulSets this isn't supported in Scylla Operator yet and it needs support from the drivers. Our own driver also needs to support manual expansion in place

```[tasklist]
- [ ] https://github.com/scylladb/k8s-local-volume-provisioner/issues/5
- [ ] https://github.com/scylladb/scylla-operator/issues/1571
- [ ] https://github.com/scylladb/scylla-operator/issues/825
```

**Comment by mflendrich** [comment]
Will be tracked in https://github.com/scylladb/scylla-operator/issues/2404.
