### ISSUE TITLE
Support automatic storage expansion

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1575]
We need a way to expand storage from the initial requests. When there is a space available on the same node we should [expand in place](https://github.com/scylladb/scylla-operator/issues/1572)

```[tasklist]
- [ ] https://github.com/scylladb/k8s-local-volume-provisioner/issues/5
- [ ] https://github.com/scylladb/scylla-operator/issues/1103
- [ ] Support setting `allowVolumeExpansion: true` for ScyllaCluster storage
- [ ] Handle failed expansions in place by node replacements in the operator
```

**Comment by mflendrich** [comment]
Will be tracked in https://github.com/scylladb/scylla-operator/issues/2401.
