### ISSUE TITLE
Support manual storage expansion with rolling replacements

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1576]
When there is no more space on the same nodes we need a procedure to change the storage request and replace node 1 by 1. (This assumes all the ScyllaDB nodes run on similar nodes so it's most likely to be group operation + we already have a single node replacement.)

```[tasklist]
- [ ] https://github.com/scylladb/scylla-operator/issues/732
- [ ] https://github.com/scylladb/scylla-operator/issues/1573
- [ ] https://github.com/scylladb/scylla-operator/issues/1574
```

**Comment by mflendrich** [comment]
Will be tracked in https://github.com/scylladb/scylla-operator/issues/2400.
