### ISSUE TITLE
Traffic stability during rolling upgrades

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1577]
This is a tracker for our epic to make sure rolling restarts are graceful and no connection gets handled ungracefully.

Unfortunately, at this point we use services that publish unready endpoints and the traffic gets errors, or gets stuck in contract tables. There are also graceful termination fixes needed for handling ScyllaDB shutdown.

```[tasklist]
- [ ] https://github.com/scylladb/scylla-operator/pull/1614
- [ ] https://github.com/scylladb/scylladb/issues/15899
- [ ] https://github.com/scylladb/scylla-operator/issues/1077
```

**Comment by mflendrich** [comment]
Will be tracked in https://github.com/scylladb/scylla-operator/issues/2399.
