### ISSUE TITLE
Docs enhancements

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1578]
```[tasklist]
- [ ] https://github.com/scylladb/scylla-operator/issues/1526
- [ ] https://github.com/scylladb/scylla-operator/issues/1785
- [ ] https://github.com/scylladb/scylla-operator/issues/1786
- [ ] #1743
- [ ] https://github.com/scylladb/scylla-operator/issues/1605
- [ ] Add architetural overview
- [ ] Structure docs into hierarchical categories
- [ ] Add API examples with descriptions (+ reference them from the intro)
- [ ] Rewrite docs about install flow
- [ ] https://github.com/scylladb/scylla-operator/issues/2084
- [ ] https://github.com/scylladb/scylla-operator/issues/2082
- [ ] Sizing ScyllaClusters to use a whole node
- [ ] https://github.com/scylladb/scylla-operator/issues/2083
- [ ] https://github.com/scylladb/scylla-operator/issues/2158
- [ ] https://github.com/scylladb/scylla-operator/issues/1465
- [ ] https://github.com/scylladb/scylla-operator/issues/1467
- [ ] Add example with custom scylla.yaml
- [ ] https://github.com/scylladb/scylla-operator/issues/2166
```
