### ISSUE TITLE
Allow configuring annotation and labels for managed resources

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1590]
We should allow defining global labels and annotation for all objects that we create and merge those with our metadata and also allow finer grained setting just for PodTemplate (e.g. for Datadog scrape labels). Also possibly identity and member services separately.

### Related Issues
- [x] #918
- [x] #1024

```[tasklist]
- [ ] https://github.com/scylladb/scylla-operator/issues/1592
- [ ] https://github.com/scylladb/scylla-operator/issues/1666
- [ ] https://github.com/scylladb/scylla-operator/issues/1668
```

**Comment by tnozicka** [comment]
done
