### ISSUE TITLE
Add periodic testing latest scylla operator with latest scylla and manager

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1611]
We should test latest operator with latest prerelease of scylladb and manager to discover possible issues early.

Requires:
- [x] https://github.com/scylladb/scylla-operator/issues/1589
```[tasklist]
### Tasks
- [ ] allow live adjusting config.yaml
- [ ] configure latest periodic
```

**Comment by mflendrich** [comment]
Will be tracked in https://github.com/scylladb/scylla-operator/issues/2330.
