### ISSUE TITLE
Secure ScyllaDB clusters by default

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1761]
Clusters in default configurations shall be secure by default.

At this point we open a lot of insecure ports that we should not start by default and use the secure variants instead. There are multiple categories of services in here:
- Some, like CQL, need to be replaced with their SSL variants and disabled
- Some need to be purely removed, like JMX or ssh
- Some might be tolerated until they have secure options (metrics mostly)
- Some are limited to localhost, like ScyllaDB API (lower prio)
- Some are fine not to have authorization, like probes (`/readyz`)

Some of the changes will take several releases to gracefully migrate over the default changes after introducing new API fields to control the ports.

All of this config is prone to small changes of version differences so this has to open ports must be validated in an e2e test.

```[tasklist]
### TODO
- [ ] #1760
- [ ] https://github.com/scylladb/scylla-operator/issues/1778
- [ ] https://github.com/scylladb/scylla-operator/issues/1762
- [ ] https://github.com/scylladb/scylla-operator/issues/1763
- [ ] https://github.com/scylladb/scylla-operator/issues/1764
- [ ] #1769
- [ ] https://github.com/scylladb/scylla-operator/issues/1217
- [ ] https://github.com/scylladb/scylla-operator/issues/1770
- [ ] https://github.com/scylladb/scylla-operator/issues/1772
- [ ] Deal with insecure metrics?
- [ ] https://github.com/scylladb/scylla-operator/issues/1805
```

**Comment by mflendrich** [comment]
Will be tracked in https://github.com/scylladb/scylla-operator/issues/2394.
