### ISSUE TITLE
Support multiple network interfaces

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1892]
Pods can have more then one network interface:
- https://cloud.google.com/anthos/clusters/docs/bare-metal/latest/how-to/multi-nic
- https://docs.aws.amazon.com/eks/latest/userguide/pod-multiple-network-interfaces.html

It should be possible to configure ScyllaClusters to use different intefaces / IPs for node-to-node, client-to-node and other traffic.

```[tasklist]
- [ ] Add design doc for configuring specific network intefaces
- [ ] Add CI support for multiple nics
- [ ] Implementation + tests + docs
```

**Comment by mflendrich** [comment]
Will be tracked in https://github.com/scylladb/scylla-operator/issues/2380.
