### ISSUE TITLE
Manager integration stability and correctness [Part 1]

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1897]
At this point, the manager integration is quite buggy and sometimes create hot loops. There is a place for improvement for testing and docs as well.

This epic is meant only to fix what we have, not to create a proper integration that respects namespaces and isolation.

```[tasklist]
### Task list
- [ ] https://github.com/scylladb/scylla-operator/issues/1739
- [ ] https://github.com/scylladb/scylla-operator/issues/1796
- [ ] https://github.com/scylladb/scylla-operator/issues/1752
- [ ] https://github.com/scylladb/scylla-operator/issues/1683
- [ ] https://github.com/scylladb/scylla-operator/issues/1694
- [ ] https://github.com/scylladb/scylla-operator/issues/1671
- [ ] https://github.com/scylladb/scylla-operator/issues/1907
```

**Comment by tnozicka** [comment]
@rzetelskik please split this into *Part 1* (this issue) that is realistic to ship for the targeted release and *Part 2* for the rest.

**Comment by rzetelskik** [comment]
@tnozicka done, https://github.com/scylladb/scylla-operator/issues/1939
please assign the priority and targeted release
