### ISSUE TITLE
Manager integration stability and correctness [Part 2]

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#1939]
Part 2 of https://github.com/scylladb/scylla-operator/issues/1897

```[tasklist]
### Task list
- [ ] https://github.com/scylladb/scylla-operator/issues/1827
- [ ] https://github.com/scylladb/scylla-operator/issues/1902
- [ ] https://github.com/scylladb/scylla-operator/issues/1869
- [ ] https://github.com/scylladb/scylla-operator/issues/1896
- [ ] https://github.com/scylladb/scylla-operator/issues/1697
- [ ] https://github.com/scylladb/scylla-operator/issues/1870
```

/kind epic
/assign

**Comment by rzetelskik** [comment]
#1827 and #1902 are kind of high priority, but we're waiting for a feature from the manager team. The rest is not as important for now imo.

**Comment by rzetelskik** [comment]
@tnozicka I also added a couple of issues that I created in the meantime, please verify if all fit here

**Comment by tnozicka** [comment]
np, I take it as a rolling one. We'll do the same dance at the end of the next release and make Part 3, if needed.

**Comment by rwnd-bradley** [comment]
I have been following the progress of this issue closely since submitting my bug report (scylladb/scylla-manager#3920). Currently, my 5 node scylla cluster experiences a constant throughput of 100-400mbps per node (not sure why it varies so much) due to scylla manager continuously checking the s3 availability (explained in the linked issue), would really like to see this resolved. I was wondering if there is a target release or a roadmap indicating when this issue might be resolved? Thank you for your hard work 🙂

**Comment by rzetelskik** [comment]
@rwnd-bradley just to add to @zimnx's comment - the lowest manager version required would be 3.3.3.
The suspected root cause was https://github.com/scylladb/scylla-operator/issues/1827 and it indeed should've been fixed in 1.15.

If the issue still persists with SO 1.15 and SM >= 3.3.3, feel free to open a new issue in our repository with [must-gather](https://operator.docs.scylladb.com/stable/support/must-gather.html) attached and we'll investigate.
