### ISSUE TITLE
Split operator auxiliary processes out of ScyllaDB container and remove the need to copy the operator binary there

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1943]
We should avoid running any operator logic in ScyllaDB container, as it's bad design and hurts ScyllaDB latency.

This will also effectively remove the hack where we copy the `scylla-operator` binary into the ScyllaDB container which takes a lot of time (init container has low cpu allocation) and significantly slows down the node start up time.

```[tasklist]
- [ ] https://github.com/scylladb/scylla-operator/issues/620
- [ ] https://github.com/scylladb/scylla-operator/issues/1941
- [ ] https://github.com/scylladb/scylla-operator/issues/1942
- [ ] https://github.com/scylladb/scylla-operator/issues/1720
- [ ] https://github.com/scylladb/scylla-operator/issues/604
- [ ] https://github.com/scylladb/scylla-operator/issues/2290
```

**Comment by mflendrich** [comment]
Will be tracked in https://github.com/scylladb/scylla-operator/issues/2326.
