### ISSUE TITLE
Release v1.15

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla-operator#2202]
### Tasks
```[tasklist]
- [ ] https://github.com/scylladb/scylla-operator/pull/2201
- [ ] https://github.com/scylladb/scylla-operator/pull/2200
- [ ] https://github.com/scylladb/scylla-operator-release/pull/347
- [ ] https://github.com/scylladb/scylla-operator/pull/2203
- [ ] https://github.com/scylladb/scylla-operator/pull/2210
- [ ] https://github.com/scylladb/scylla-operator/issues/2180
- [ ] https://github.com/scylladb/scylla-operator/issues/2213
- [ ] https://github.com/scylladb/scylla-operator/issues/2216
- [ ] https://github.com/scylladb/scylla-operator/pull/2252
- [ ] https://github.com/scylladb/scylla-operator/pull/2250
- [ ] https://github.com/scylladb/scylla-operator/issues/2270
- [ ] https://github.com/scylladb/scylla-operator/issues/2217
```
