### ISSUE TITLE
Add must-gather command for gathering all necessary info 

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#856]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Collect all related API objects in the cluster + logs.

**What is use case behind this feature:**
When a user submits a bug report there is a frequent ping pong to get the necessary YAML dumps and logs for debugging. Having a command that collects all the necessary objects (without user's secrets) will avoid that ping pong and allows us to provide faster responses without wasting time of both parties involved.

**Additional Information:**
We can potentially also add `analyze` command taking this dump an checking for common failures, like some of the components being not available.

```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylla-operator/issues/1365
- [ ] https://github.com/scylladb/scylla-operator/issues/1367
- [ ] https://github.com/scylladb/scylla-operator/issues/1366
```

**Comment by tnozicka** [comment]
done in v1.11
